# Generated by Django 6.0 on 2025-12-22 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('car_type', models.CharField(choices=[('porter', 'Hyundai Porter'), ('gazel', 'Газель'), ('labo', 'Labo'), ('bort', 'Бортовая')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=20)),
                ('point_a', models.CharField(max_length=200)),
                ('point_b', models.CharField(max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('service_fee', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('assigned', 'Назначен водитель'), ('done', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.driver')),
            ],
        ),
    ]
