# Generated by Django 6.0 on 2025-12-24 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Водитель', 'verbose_name_plural': 'Водители'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='driver',
            name='car_type',
            field=models.CharField(choices=[('porter', 'Hyundai Porter'), ('gazel', 'Газель'), ('labo', 'Labo'), ('bort', 'Бортовая')], max_length=20, verbose_name='Тип машины'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Имя клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='order',
            name='point_a',
            field=models.CharField(max_length=200, verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='point_b',
            field=models.CharField(max_length=200, verbose_name='Куда'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_fee',
            field=models.IntegerField(blank=True, null=True, verbose_name='Наша комиссия'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('assigned', 'Назначен водитель'), ('done', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общая стоимость'),
        ),
    ]
